# Generated by Django 5.2.5 on 2025-09-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
